export const FIRST_NAME_CHANGE= "FIRST_NAME_CHANGE";
export const LAST_NAME_CHANGE= "LAST_NAME_CHANGE";
export const MOBILE_NUMBER_CHANGE= "MOBILE_NUMBER_CHANGE";
export const EMAIL_CHANGE= "EMAIL_CHANGE";

